Add mini-app example
CartoDB/web-sdk pull request #90
Opened 2020-07-17 07:21 UTC by borja-munoz

Add the mini-app example to the examples/_debug folder

2020-07-17 11:31 UTC, VictorVelarde commented
Vercel is available now: https://web-sdk-git-feature-include-miniapp-example.carto-frontend.now.sh/examples/_debug/mini-app/mini-app.html

I have seen some small changes we need to make before merging, as right now we have some issues (event renames...). I will review it during the next week, after the release

2020-07-17 14:14 UTC, manmorjim requested changes

2020-07-17 14:14 UTC, manmorjim commented on examples/_debug/mini-app/mini-app.html
> +                    format: '.4s'
this D3 format is not available anymore

2020-07-17 14:23 UTC, borja-munoz commented on examples/_debug/mini-app/mini-app.html
> +                    format: '.4s'
Fixed

2020-07-27 16:52 UTC, VictorVelarde approved these changes
LGTM.

2020-07-27 17:15 UTC, merged